vich_uploader:
    db_driver: orm

    mappings:
        kbis_upload:
            uri_prefix: /uploads/kbis
            upload_destination: "%kernel.project_dir%/public/uploads/kbis"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: true
