name: Staging deployment

on:
  push:
    tags:
      - "stage-*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v4

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - name: Get tag name
        uses: olegtarasov/get-tag@v2.1.3

      - name: GitHub Action for DigitalOcean - doctl
        uses: digitalocean/action-doctl@v2.5.1
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Provision Droplet and deploy container
        run: doctl compute create "$GIT_TAG_NAME" --image docker-22-04 --size s-1vcpu-1gb --region sfo3 --user-data-file deploy.sh --wait
