name: Staging deployment

on:
  push:
    tags:
      - "stage-*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v4

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - name: Get tag name
        uses: olegtarasov/get-tag@v2.1.3

      - name: GitHub Action for DigitalOcean - doctl
        uses: digitalocean/action-doctl@v2.5.1
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: whoami

      - name: Provision Droplet and deploy container
        run: |
          rsync -av --delete --exclude='.git' . root@143.244.189.241:/root
          doctl compute droplet-action rename 413683266 --droplet-name "$GIT_TAG_NAME"
          doctl compute ssh 413683266 --ssh-command "bash deploy.sh"
