on:
  push:
    branches:
      - main
      - develop

jobs:
  test_api_plateform:
    name: ci backend
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, curl, pdo, sqlite, zip, pcntl
          coverage: none
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Change directory
        run: cd api-plateform/api

      - name: Install dependencies
        run: composer install
        working-directory: api-plateform/api

      - name: Run PHP_CodeSniffer (PHPCS)
        run: vendor/bin/phpcs src/
        working-directory: api-plateform/api

      - name: Run PHPStan
        run: vendor/bin/phpstan.phar analyse src/ -c phpstan.neon --level=max --no-progress -vvv --memory-limit=2048M
        working-directory: api-plateform/api
  frontend_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies and Format code with Prettier
        run: |
          npm ci
          npm run format

      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            git clone git@github.com:Bass913/Pilot.git
            cd Pilot
            SERVER_NAME=challenge.pilot.us.to \
            APP_SECRET=ChangeMe \
            POSTGRES_PASSWORD=ChangeMe \
            CADDY_MERCURE_JWT_SECRET=ChangeThisMercureHubJWTSecretKey \
            docker compose -f compose.yaml -f compose.prod.yaml up --wait
