on:
  push:
    tags:
      - "stage-*"

jobs:
  frontend_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies and Format code with Prettier
        run: |
          npm ci
          npm run format

  deploy:
    needs: test_api_plateform
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}

          script: |
            mkdir test
            cd test
            git clone git@github.com:Bass913/Pilot.git
            echo 'Deployment succesful to digital ocean'

      - name: Get tag name
        uses: olegtarasov/get-tag@v2.1.3

      - name: GitHub Action for DigitalOcean - doctl
        uses: digitalocean/action-doctl@v2.5.1

        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          working-directory: /home/Pilot

      - name: Provision Droplet and deploy container
        run: |
          doctl compute droplet-action rename 413683266 --droplet-name "$GIT_TAG_NAME"
