vich_uploader:
    db_driver: orm

    mappings:
        kbis:
            uri_prefix: /kbis
            upload_destination: "%kernel.project_dir%/public/kbis"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
